### ISSUE TITLE
hang after long usage in heavy web pages

### ISSUE THREAD

**Issue by mckaygerhard** [moonsteal/moonbrowser#1]
it seems cos lua are non threat.. so if i open many instances one hangs.. maybe is beter to embed the chromium engine sandbox and just make a frontend..

**Comment by mckaygerhard** [comment]
ah it seems GTKwebkit problem as i said is better a good usage of the sandbox of chromiun

**Comment by sodomon2** [comment]
> ah it seems GTKwebkit problem as i said is better a good usage of the sandbox of chromiun

This is impossible since the chromium sandbox does not have bindings for lua

**Comment by sodomon2** [comment]
> it seems cos lua are non threat.. so if i open many instances one hangs.. maybe is beter to embed the chromium engine sandbox and just make a frontend..

I don't understand what would be the idea of opening several instances of moonbrowser

Tabs are already in development, which means that there will be no need to open several instances and the application will not hang.

**Comment by mckaygerhard** [comment]
> This is impossible since the chromium sandbox does not have bindings for lua

umm that's true.. but so.. what the idea of a non-working browser?
